### ISSUE TITLE
LCD Type

### ISSUE THREAD

**Issue by micha-uhl** [funnypolynomial/ArDSKYlite#1]
Hallo, should this work:
![s-l1600-2](https://github.com/user-attachments/assets/a830803d-8463-460a-a7b4-cc3f459661a6)

Michael

**Comment by funnypolynomial** [comment]
The back looks almost identical to mine, so yes, it should _probably_ work.

**Comment by micha-uhl** [comment]
I got the display, but it doesn't work, only colorful flicker. It has the driver IC ST7789V. What can I do?
![IMG_3608](https://github.com/user-attachments/assets/e2a0feda-c5b3-4e58-9a3f-6a203664aa85)

**Comment by funnypolynomial** [comment]
Ah yes, the front is quite different. Incompatible hardware I'm afraid.
If you can write/find functions that:
1) initialise the display
2) define a window on the display (x, y, width, height)
3) send n colour words to the display
4) get touch (x, y)

then you could probably change LCD.cpp to work.

**Comment by micha-uhl** [comment]
Ein Elegoo ILI9341 funktioniert auch nicht.

**Comment by funnypolynomial** [comment]
"An Elegoo ILI9341 doesn't work either."
Sorry, not much I can do.
